version: "3"
services:
  db-backend-winter-postgres:
    image: postgres:14.5
    restart: unless-stopped
    container_name: db-backend-winter-postgres
    volumes:
      - pgBackendWinterData:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment: 
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    networks:
      - default

volumes:
  pgBackendWinterData: